# Generated by Django 4.1.1 on 2022-10-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDonar', '0003_mascota_imagen_ropa_imagen_utensilio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ropa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
